### ISSUE TITLE
sub folders for different language muxes

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#26]
We should either place all muxes in one dir and and the master in another or create a dir per language.

**Comment by derpeter** [comment]
@a-tze what are your thoughts on this?

**Comment by a-tze** [comment]
Status quo is: 
  - master is in one dir, e.g. h264-hd
  - single language muxes in h264-html5

right? Then I think we do currently have the first variant you described.

Since we actually just wait for the browsers to be capable of handling multi-audio-track files to get rid of the -html files, I see little reason to change the behaviour, because now we have exactly all the files that can be deleted in one directory.

Changing the dir structure only helps users who browse the CDN directly. I'm not aware of any feedback of such users. That doesnt mean that there is no such feedback, I simply have no knowledge of it.

So either I dont understand your thoughts correctly or there is no need for a change in my opinion.

**Comment by derpeter** [comment]
I'm still unsure what to do here. Do we stay with the current state or do we want a different behavior?
@manno any thoughts on this?

**Comment by manno** [comment]
@a-tze I would have never imagined we can get rid of html encodes, since they are so special:

* limited codecs, and I think also limited codec capabilities 
* interleaved
* single audio track
* good quality for streaming / file size

But maybe we can, maybe one day browsers support all the features and we find a player that is able to select just the right file for the users screen resolution, bandwidth, etc.
On the other hand we have an increasing number of clients, like Kodi, Apple TV, Android and now Enigma2. It might make sense to keep a basic 'html'-style encode  around for those.

@derpeter why do you want to change the folders? Just to make it easier for CDN users to download all videos with 'their' language?

**Comment by derpeter** [comment]
we discussed this again at 34c3 and kind of agreed to sit this out and wait until we dont need the single audio muxe anymore
